### ISSUE TITLE
Shouldn't try to connect to "postgres" database; only to databases configured in database.yml

### ISSUE THREAD

**Issue by fugue88** [atomicjolt/adhesion#116]
```
[app1] + load_adhesion_database
[app1] + pushd /var/adhesion
[app1] /var/adhesion /
[app1] + RAILS_ENV=production
[app1] + rake db:setup
[app1] FATAL:  no pg_hba.conf entry for host "192.168.13.101", user "adhesion", database "postgres", SSL on
[app1] FATAL:  no pg_hba.conf entry for host "192.168.13.101", user "adhesion", database "postgres", SSL off
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
[app1] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
[app1] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:87:in `connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:93:in `create'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
[app1] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
[app1] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
[app1] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
[app1] /usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
[app1] /usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
[app1] /usr/bin/rake:27:in `<main>'
```

**Comment by bfcoder** [comment]
What does your database.yml look like?

**Comment by bfcoder** [comment]
Rails only uses data from database.yml. So the only thing I can figure is you have a rogue database.yml somewhere. There is nothing in adhesion that configures otherwise. Closing for now.
