### ISSUE TITLE
Shouldn't try to create schema that already exists

### ISSUE THREAD

**Issue by fugue88** [atomicjolt/adhesion#118]
```
[app1] rake aborted!
[app1] Apartment::TenantExists: Error while creating tenant scorm-player: PG::DuplicateSchema: ERROR:  schema "scorm-player" already exists
[app1] : CREATE SCHEMA "scorm-player"
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:283:in `raise_create_tenant_error!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:174:in `rescue in create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:170:in `create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:24:in `block in create'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:23:in `create'
[app1] /var/adhesion/app/models/lti_application_instance.rb:31:in `create_schema'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `block in call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `each'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:306:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/timestamp.rb:57:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:504:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:117:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:505:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:142:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:43:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `block in save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:51:in `create!'
[app1] /var/adhesion/db/seeds.rb:112:in `block in <top (required)>'
[app1] /var/adhesion/db/seeds.rb:103:in `each'
[app1] /var/adhesion/db/seeds.rb:103:in `<top (required)>'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `block in load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:547:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
[app1] ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "scorm-player" already exists
[app1] : CREATE SCHEMA "scorm-player"
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:78:in `create_tenant_command'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:171:in `block in create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:270:in `with_neutral_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:170:in `create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:24:in `block in create'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:23:in `create'
[app1] /var/adhesion/app/models/lti_application_instance.rb:31:in `create_schema'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `block in call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `each'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:306:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/timestamp.rb:57:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:504:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:117:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:505:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:142:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:43:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `block in save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:51:in `create!'
[app1] /var/adhesion/db/seeds.rb:112:in `block in <top (required)>'
[app1] /var/adhesion/db/seeds.rb:103:in `each'
[app1] /var/adhesion/db/seeds.rb:103:in `<top (required)>'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `block in load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:547:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
[app1] PG::DuplicateSchema: ERROR:  schema "scorm-player" already exists
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:78:in `create_tenant_command'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:171:in `block in create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:270:in `with_neutral_connection'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:170:in `create_tenant'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:24:in `block in create'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:23:in `create'
[app1] /var/adhesion/app/models/lti_application_instance.rb:31:in `create_schema'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `block in call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `each'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:506:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:306:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/timestamp.rb:57:in `_create_record'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:504:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `block in create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:117:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:505:in `call'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/callbacks.rb:302:in `create_or_update'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:142:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/validations.rb:43:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `block in save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:291:in `save!'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/persistence.rb:51:in `create!'
[app1] /var/adhesion/db/seeds.rb:112:in `block in <top (required)>'
[app1] /var/adhesion/db/seeds.rb:103:in `each'
[app1] /var/adhesion/db/seeds.rb:103:in `<top (required)>'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `block in load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:547:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'
[app1] /var/adhesion-gems/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
[app1] Tasks: TOP => db:setup => db:seed
[app1] (See full trace by running task with --trace)
```

**Comment by bfcoder** [comment]
@fugue88 I don't believe you are running the latest adhesion. You have old code if it is trying to access `app/models/lti_application_instance.rb`

**Comment by bfcoder** [comment]
Also, why are you using ruby 2.3.0? You should be using 2.3.1.

**Comment by bfcoder** [comment]
I get the same issue when running `rake db:setup`

**Comment by bfcoder** [comment]
fixed with https://github.com/atomicjolt/adhesion/commit/127f8ae1263aa2aa33ec00d280e6ac5ab936c550
